services:
  grafana:
    build:
      args:
        grafana_version: ${GRAFANA_VERSION:-10.4.14}
    volumes:
      # The built plugin
      # Volume for persisting changes
      - grafana:/var/lib/grafana
      # For shared AWS config and credentials files
      - ~/.aws:/usr/share/grafana/.aws

    environment:
      # Specifies the location of the file that the AWS CLI uses to store configuration profiles
      AWS_CONFIG_FILE: /usr/share/grafana/.aws/config
      # Specifies the location of the file that the AWS CLI uses to store access keys
      AWS_SHARED_CREDENTIALS_FILE: /usr/share/grafana/.aws/credentials
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana

volumes:
  grafana:
