import React from 'react';
import { Alert, Box, Text } from '@grafana/ui';
import { ValidationError } from './types';

interface Props {
  preview: string;
  errors: ValidationError[];
}

/**
 * Displays a query preview using a styled Text component.
 *
 * This is typically used to show the final SQL or expression string
 * generated by a SQL builder. If there are validation or syntax errors,
 * the text color changes to indicate the error state.
 * generated by a SQL builder, along with validation or syntax errors.
 *
 * @param preview - the rendered SQL or query string
 * @param errors - list of errors to determine text color
 */
export const QueryPreviewDisplay: React.FC<Props> = ({ preview, errors }) => {
  const severity = errors.length > 0 ? 'error' : 'info';

  return (
    <Box marginTop={2}>
      <Alert title="Query Preview" severity={severity}>
        <Text variant="code" color={severity}>
          {preview}
        </Text>
      </Alert>
    </Box>
  );
};
