import React from 'react';
import { Alert } from '@grafana/ui';

interface Props {
  preview: string;
  errors: string[];
}

// Style for the outer container wrapping the alert box
const containerStyle: React.CSSProperties = {
  marginTop: '1rem',
};

// Style for the list of error messages
const errorListStyle: React.CSSProperties = {
  paddingLeft: '1.2em',
  margin: 0,
  marginBottom: '0.5em',
};

// Style for each individual error message item
const errorItemStyle: React.CSSProperties = {
  fontSize: 12,
};

// Style for the query preview text block
const previewStyle: React.CSSProperties = {
  fontSize: 12,
  padding: 0,
  margin: 0,
  backgroundColor: 'transparent',
  border: 'none',
  whiteSpace: 'pre-wrap',
  wordBreak: 'break-word',
};

/**
 * Displays a query preview with optional error messages inside a styled Alert box.
 *
 * This is typically used to show the final SQL or expression string
 * generated by a SQL builder, along with validation or syntax errors.
 *
 * @param preview - the rendered SQL or query string
 * @param errors - list of error messages to display (if any)
 */
export const QueryPreviewDisplay: React.FC<Props> = ({ preview, errors }) => {
  const hasErrors = errors.length > 0;
  const title = hasErrors ? 'Query Errors & Preview' : 'Query Preview';
  const severity = hasErrors ? 'error' : 'info';

  return (
    <div style={containerStyle}>
      <Alert title={title} severity={severity}>
        {hasErrors && (
          <ul style={errorListStyle}>
            {errors.map((error, index) => (
              <li key={index} style={errorItemStyle}>
                {error}
              </li>
            ))}
          </ul>
        )}
        <pre style={previewStyle}>{preview}</pre>
      </Alert>
    </div>
  );
};
