import React from 'react';
import { Alert } from '@grafana/ui';
import { ValidationError } from './types';

interface Props {
  preview: string;
  errors: ValidationError[];
}

// Style for the outer container wrapping the alert box
const containerStyle: React.CSSProperties = {
  marginTop: '1rem',
};

// Style for the query preview text block
const previewStyle: React.CSSProperties = {
  fontSize: 12,
  padding: 0,
  margin: 0,
  backgroundColor: 'transparent',
  border: 'none',
  whiteSpace: 'pre-wrap',
  wordBreak: 'break-word',
};

/**
 * Displays a query preview with optional error messages inside a styled Alert box.
 *
 * This is typically used to show the final SQL or expression string
 * generated by a SQL builder, along with validation or syntax errors.
 *
 * @param preview - the rendered SQL or query string
 * @param errors - list of error messages to display (if any)
 */
export const QueryPreviewDisplay: React.FC<Props> = ({ preview, errors }) => {
  const hasErrors = errors.length > 0;
  const severity = hasErrors ? 'error' : 'info';

  return (
    <div style={containerStyle}>
      <Alert title="Query Preview" severity={severity}>
        <pre style={previewStyle}>{preview}</pre>
      </Alert>
    </div>
  );
};
