name: E2E tests
on:
  pull_request:

permissions:
  contents: read

jobs:
  resolve-versions:
    name: Resolve Grafana images
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      matrix: ${{ steps.resolve-versions.outputs.matrix }}
    steps:
      - name: Resolve Grafana E2E versions
        id: resolve-versions
        uses: grafana/plugin-actions/e2e-version@c233e9f6752186a9b256a2a451ec3067fbf712c2 # main
        with:
          version-resolver-type: version-support-policy

  playwright-tests:
    needs: resolve-versions
    permissions:
      id-token: write
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        GRAFANA_IMAGE: ${{fromJson(needs.resolve-versions.outputs.matrix)}}
    name: e2e ${{ matrix.GRAFANA_IMAGE.name }}@${{ matrix.GRAFANA_IMAGE.VERSION }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          persist-credentials: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version-file: .nvmrc

      - name: Install Mage
        uses: magefile/mage-action@6f50bbb8ea47d56e62dee92392788acbc8192d0b # v3.1.0
        with:
          install-only: true

      - name: Install yarn dependencies
        run: yarn install

      - name: Build binaries
        run: mage -v build:linux

      - name: Build frontend
        run: yarn build

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Start Grafana
        run: |
          docker compose pull
          GRAFANA_VERSION=${{ matrix.GRAFANA_IMAGE.VERSION }} GRAFANA_IMAGE=${{ matrix.GRAFANA_IMAGE.NAME }} docker compose up -d

      - name: Wait for Grafana to start
        uses: grafana/plugin-actions/wait-for-grafana@main

      - name: Get secrets for e2e tests and set in env
        id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@main
        with:
          repo_secrets: |
            AWS_ACCESS_KEY=e2e:AWS_ACCESS_KEY
            AWS_SECRET_KEY=e2e:AWS_SECRET_KEY

      - name: Run E2E tests
        id: run-tests
        run: yarn run e2e
